CREATE TABLE classes(id SERIAL PRIMARY KEY, name varchar NOT NULL);

CREATE TABLE sessions(id SERIAL PRIMARY KEY, class integer NOT NULL);

GRANT SELECT, INSERT, UPDATE, DELETE ON classes TO angell;
GRANT SELECT, INSERT, UPDATE, DELETE ON sessions TO angell;
